doctrine_orm_bridge:
    entity_manager: default
    connection: default

command_bus:
    logging: true
    command_name_resolver_strategy: named_message

event_bus:
    logging: true
    event_name_resolver_strategy: named_message
