lexik_jwt_authentication:
    private_key_path: %kernel.root_dir%/private.pem
    public_key_path:  %kernel.root_dir%/public.pem
    pass_phrase:      '1234'
    token_ttl:        86400

# openssl genrsa -out app/var/jwt/private.pem -aes256 4096
# openssl rsa -pubout -in app/var/jwt/private.pem -out app/var/jwt/public.pem

# https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md